# docker-compose version
version: "3.6"

volumes:
  postgres-volume:

networks:
  postgres:

services:
  postgres:
    image: postgres:13
    container_name: postgresdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    networks:
      - postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      # copy the sql script to create tables
      # - ./prisma/migrations/20220320011333_init/migration.sql:/docker-entrypoint-initdb.d/create_tables.sql

  client:
    stdin_open: true # needed to allow react-scripts to watch for changes
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - postgres
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/mydb"
      NEXT_PUBLIC_SUPABASE_URL: https://qmgmihsqoaaznattjbkl.supabase.co
      NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtZ21paHNxb2Fhem5hdHRqYmtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDgzMjcwNDAsImV4cCI6MTk2MzkwMzA0MH0.k1ard8bxmmWzPlJ2efCT4kkQ7LbcZAwMpgtQ2PcL7R8
